---

services:
  hapi:
    image: hapiproject/hapi:v7.0.3
    container_name: hapi
    ports:
      - 8080:8080
    volumes:
      - ./application.yaml:/app/config/application.yaml
    restart: no

  jbpm_db:
    image: postgres
    container_name: jbpm_db
    ports:
      - 5432:5432
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: consentimientos
      POSTGRES_USER: jbpm
      POSTGRES_PASSWORD: jbpm
    restart: no

  adminer:
    image: adminer
    ports:
      - 3000:8080
    restart: no
